### ISSUE TITLE
Shutdown doesn't work

### ISSUE THREAD

**Issue by casept** [casept/linux-samsung-smartwatch#9]
The display at least still seems to be active after a shutdown, so we're possibly missing something required to finalize shutdown.

Reboot works fine.

**Comment by casept** [comment]
Samsung wiggles a magic PMU register in the downstream kernel at https://github.com/casept/samsung-rinato-sources/blob/master/kernel/arch/arm/mach-exynos/sec_reboot.c#L43 .

The mainline kernel defines related registers in `include/linux/soc/samsung/exynos-regs-pmu.h`.

**Comment by casept** [comment]
Seems like there's no power-off driver for any Exynos platform in mainline, the PMU driver only implements suspend. Will try writing one.

**Comment by PabloPL** [comment]
On Galaxy S1 (s5pv210) which also requires writing specific value to specific register, we did used **syscon-poweroff** driver. Maybe this could be used also in this case. Here is link to dts node https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/samsung/s5pv210-aries.dtsi#L541

**Comment by PabloPL** [comment]
Also that code on https://github.com/casept/samsung-rinato-sources/blob/master/kernel/arch/arm/mach-exynos/sec_reboot.c#L43 - isn't it doing LP charging mode instead of power off which is at https://github.com/casept/samsung-rinato-sources/blob/master/kernel/arch/arm/mach-exynos/sec_reboot.c#L62 ?

**Comment by PabloPL** [comment]
Or maybe just include exynos-syscon-restart.dtsi like all other exynos based devices in mainline.

**Comment by casept** [comment]
I've implemented a driver now, and power off seems to work. Might be possible to solve this more elegantly by using the syscon-poweroff DT node instead.
